function [y,yz,yzi] = autoGen_cst_swingFootHeight(q1,q2,q4,q5,l1,l2,l4,l5,stepLength,stepHeight)
%AUTOGEN_CST_SWINGFOOTHEIGHT
%    [Y,YZ,YZI] = AUTOGEN_CST_SWINGFOOTHEIGHT(Q1,Q2,Q4,Q5,L1,L2,L4,L5,STEPLENGTH,STEPHEIGHT)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Jul-2021 10:06:20

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q4);
t5 = cos(q5);
t6 = sin(q1);
t7 = sin(q2);
t8 = sin(q4);
t9 = sin(q5);
t14 = 1.0./stepLength.^2;
t10 = l1.*t6;
t11 = l2.*t7;
t12 = l4.*t8;
t13 = l5.*t9;
t15 = -t12;
t16 = -t13;
t17 = t10+t11+t15+t16;
y = -l1.*t2-l2.*t3+l4.*t4+l5.*t5-stepHeight.*(t14.*t17.^2-1.0);
if nargout > 1
    yz = [t10-l1.*stepHeight.*t2.*t14.*t17.*2.0;t11-l2.*stepHeight.*t3.*t14.*t17.*2.0;t15+l4.*stepHeight.*t4.*t14.*t17.*2.0;t16+l5.*stepHeight.*t5.*t14.*t17.*2.0];
end
if nargout > 2
    yzi = [2.0;3.0;5.0;6.0];
end
