function [c,cz,czi] = autoGen_cst_costOfTransport(dq1,dq2,dq3,dq4,dq5,u1,u2,u3,u4,u5,sn1,sn2,sn3,sn4,sn5,sp1,sp2,sp3,sp4,sp5,empty)
%AUTOGEN_CST_COSTOFTRANSPORT
%    [C,CZ,CZI] = AUTOGEN_CST_COSTOFTRANSPORT(DQ1,DQ2,DQ3,DQ4,DQ5,U1,U2,U3,U4,U5,SN1,SN2,SN3,SN4,SN5,SP1,SP2,SP3,SP4,SP5,EMPTY)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    12-Jul-2021 10:06:18

t2 = empty+1.0;
t3 = -dq2;
t4 = -dq3;
t5 = -dq4;
c = [sn1-sp1+dq1.*u1;sn2-sp2-u2.*(dq1+t3);sn3-sp3-u3.*(dq2+t4);sn4-sp4-u4.*(dq3+t5);sn5-sp5-u5.*(dq4-dq5)];
if nargout > 1
    t6 = empty-1.0;
    cz = [u1;-u2;u2;-u3;u3;-u4;u4;-u5;u5;dq1;-dq1+dq2;dq3+t3;dq4+t4;dq5+t5;t2;t2;t2;t2;t2;t6;t6;t6;t6;t6];
end
if nargout > 2
    czi = [3.1e+1;3.2e+1;3.7e+1;3.8e+1;4.3e+1;4.4e+1;4.9e+1;5.0e+1;5.5e+1;5.6e+1;6.2e+1;6.8e+1;7.4e+1;8.0e+1;1.06e+2;1.12e+2;1.18e+2;1.24e+2;1.3e+2;1.31e+2;1.37e+2;1.43e+2;1.49e+2;1.55e+2];
end
